version: '3'
services:
    client:
        image: 'jbpino/ts-react-app_client'
        build: .
        restart: always
        container_name: react-client
        ports:
            - '3005:80'
        networks:
            - webappnetwork
    api:
        image: 'jbpino/ts-react-app_api'
        build: ./backend
        restart: always
        container_name: mongodb-api
        environment:
            - MONGO_DB_URI=${MONGO_DB_URI}
        ports:
            - '7000:7000'
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes: []
        ports:
            - 27017:27017
        networks:
            - webappnetwork
    #creating a service called admin-mongo in case you want to connect and manage your mongodb locally
    #currently using mondogb atlas connection string so admin-mongodb doesn't need to be active
    # admin-mongodb:
    #   #pull down the official image from DockerHub registry
    #   image: 0x59/admin-mongo:latest
    #   ports:
    #     - "8082:8082"
    #   environment:
    #     - PORT=8082
    #     - CONN_NAME=mongodb
    #     - DB_HOST=mongodb
    #   networks:
    #       - webappnetwork
networks:
    webappnetwork:
        driver: bridge
